include ../Makedefs

all :
	$(MAKE) -C common all
	$(MAKE) -C rtt all
	$(MAKE) -C oit all
	$(MAKE) -C oix all

clean :
	$(MAKE) -C common clean
	$(MAKE) -C rtt clean
	$(MAKE) -C oix clean
	$(MAKE) -C oit clean

etags :
	$(MAKE) -C common etags
	$(MAKE) -C h etags
	$(MAKE) -C rtt etags
	$(MAKE) -C oix etags
	$(MAKE) -C oit etags
