<../../mkdefs

ROBJS = rttparse_mod.$O rttmain.$O rttlex.$O rttsym.$O rttnode.$O rttout.$O rttmisc.$O\
	icontype.$O rttdb.$O yyerror.$O \
	pout.$O pchars.$O  perr.$O pmem.$O  bldtok.$O macro.$O \
	preproc.$O evaluate.$O files.$O gettok.$O pinit.$O

COBJS = ../common/getopt.$O ../common/alloc.$O \
	  ../common/strtbl.$O ../common/plan9.$O \
	  ../common/mlocal.$O

OBJS = $ROBJS $COBJS

PROG=		../../bin/rtt

all:V:   $PROG

$PROG:	$OBJS
	$LD -o $PROG $OBJS

$ROBJS: rtt.h rtt1.h rttproto.h preproc.h pproto.h ltoken.h ../h/mproto.h\
	        ../h/define.h ../h/config.h ../h/typedefs.h \
	        ../h/cstructs.h

rttdb.$O: ../h/version.h
rttparse_mod.$O : ../h/gsupport.h ../h/config.h ../h/cstructs.h \
	../h/typedefs.h ../h/define.h

clean:V:
	rm -f *.[$OS] [$OS].out rttparse_mod.c $PROG

rttparse_mod.c: rttparse.c
	sed -e 's/^#include <stdlib.h>.*$//'  \
		-e 's/^#include <string.h>.*$//' rttparse.c >rttparse_mod.c
