/*
 * This file was generated by the program typespec.
 */

int str_typ = 0;
int int_typ = 1;
int rec_typ = 2;
int proc_typ = 7;
int coexp_typ = 8;
int stv_typ = 9;
int ttv_typ = 10;
int null_typ = 11;
int cset_typ = 12;
int real_typ = 13;
int list_typ = 14;
int tbl_typ = 15;

int num_typs = 24;
struct icon_type icontypes[24] = {
  {"string", 0, DrfNone, TRetSpcl, NULL, 0, 0, "s", "String"},
  {"integer", 0, DrfNone, TRetNone, NULL, 0, 0, "i", "Integer"},
  {"record", 0, DrfNone, TRetBlkP, NULL, 0, 0, "R", "Record"},
  {"class", 0, DrfNone, TRetBlkP, NULL, 0, 0, "class", "Class"},
  {"object", 0, DrfNone, TRetBlkP, NULL, 0, 0, "object", "Object"},
  {"cast", 0, DrfNone, TRetBlkP, NULL, 0, 0, "cast", "Cast"},
  {"methp", 0, DrfNone, TRetBlkP, NULL, 0, 0, "methp", "Methp"},
  {"proc", 0, DrfNone, TRetBlkP, NULL, 0, 0, "proc", "Proc"},
  {"coexpr", 0, DrfNone, TRetBlkP, NULL, 0, 0, "C", "Coexpr"},
  {"tvsubs", 1, DrfSpcl, TRetSpcl, NULL, 1, 0, "sstv", "Tvsubs"},
  {"tvtbl", 1, DrfSpcl, TRetBlkP, NULL, 1, 1, "tetv", "Tvtbl"},
  {"null", 0, DrfNone, TRetNone, NULL, 0, 0, "n", "Null"},
  {"cset", 0, DrfNone, TRetBlkP, NULL, 0, 0, "c", "Cset"},
  {"real", 0, DrfNone, TRetBlkP, NULL, 0, 0, "r", "Real"},
  {"list", 1, DrfNone, TRetBlkP, NULL, 1, 2, "L", "List"},
  {"table", 1, DrfNone, TRetBlkP, NULL, 3, 3, "T", "Table"},
  {"file", 0, DrfNone, TRetBlkP, NULL, 0, 0, "f", "File"},
  {"set", 1, DrfNone, TRetBlkP, NULL, 1, 6, "S", "Set"},
  {"kywdint", 0, DrfCnst, TRetDescP, ".i......................", 0, 0, "kywdint", "Kywdint"},
  {"kywdsubj", 0, DrfCnst, TRetDescP, "s.......................", 0, 0, "kywdsubj", "Kywdsubj"},
  {"kywdpos", 0, DrfCnst, TRetDescP, ".i......................", 0, 0, "kywdpos", "Kywdpos"},
  {"kywdevent", 0, DrfCnst, TRetDescP, "siRcocmpC..ncrLTfS......", 0, 0, "kywdevent", "Kywdevent"},
  {"kywdwin", 0, DrfCnst, TRetDescP, "...........n....f.......", 0, 0, "kywdwin", "Kywdwin"},
  {"kywdstr", 0, DrfCnst, TRetDescP, "s.......................", 0, 0, "kywdstr", "Kywdstr"}};

int str_var = 0;
int trpd_tbl = 1;
int lst_elem = 2;
int tbl_dflt = 5;
int tbl_val = 4;

int num_cmpnts = 7;
struct typ_compnt typecompnt[7] = {
  {"str_var", 0, 0, 9, NULL},
  {"trpd_tbl", 0, 0, 10, NULL},
  {"lst_elem", 0, 1, 14, "LE"},
  {"tbl_key", 0, 0, 15, NULL},
  {"tbl_val", 1, 1, 15, "TV"},
  {"tbl_dflt", 2, 0, 15, NULL},
  {"set_elem", 0, 0, 17, NULL}};
