/*
 * This file was generated by the program typespec.
 */

#include "rtt.h"

int str_typ = 0;
int int_typ = 1;
int rec_typ = 2;
int proc_typ = 9;
int coexp_typ = 10;
int stv_typ = 11;
int ttv_typ = 12;
int null_typ = 13;
int cset_typ = 15;
int real_typ = 16;
int list_typ = 17;
int tbl_typ = 18;
int ucs_typ = 7;

int num_typs = 26;
struct icon_type icontypes[26] = {
  {"string", 0, DrfNone, TRetSpcl, NULL, 0, 0, "s", "String"},
  {"integer", 0, DrfNone, TRetNone, NULL, 0, 0, "i", "Integer"},
  {"record", 0, DrfNone, TRetBlkP, NULL, 0, 0, "R", "Record"},
  {"class", 0, DrfNone, TRetBlkP, NULL, 0, 0, "class", "Class"},
  {"object", 0, DrfNone, TRetBlkP, NULL, 0, 0, "object", "Object"},
  {"methp", 0, DrfNone, TRetBlkP, NULL, 0, 0, "methp", "Methp"},
  {"constructor", 0, DrfNone, TRetBlkP, NULL, 0, 0, "constructor", "Constructor"},
  {"ucs", 0, DrfNone, TRetBlkP, NULL, 0, 0, "ucs", "Ucs"},
  {"weakref", 0, DrfNone, TRetBlkP, NULL, 0, 0, "weakref", "Weakref"},
  {"proc", 0, DrfNone, TRetBlkP, NULL, 0, 0, "proc", "Proc"},
  {"coexpr", 0, DrfNone, TRetBlkP, NULL, 0, 0, "C", "Coexpr"},
  {"tvsubs", 1, DrfSpcl, TRetBlkP, NULL, 1, 0, "sstv", "Tvsubs"},
  {"tvtbl", 1, DrfSpcl, TRetBlkP, NULL, 1, 1, "tetv", "Tvtbl"},
  {"null", 0, DrfNone, TRetNone, NULL, 0, 0, "n", "Null"},
  {"yes", 0, DrfNone, TRetNone, NULL, 0, 0, "yes", "Yes"},
  {"cset", 0, DrfNone, TRetBlkP, NULL, 0, 0, "c", "Cset"},
  {"real", 0, DrfNone, TRetBlkP, NULL, 0, 0, "r", "Real"},
  {"list", 1, DrfNone, TRetBlkP, NULL, 1, 2, "L", "List"},
  {"table", 1, DrfNone, TRetBlkP, NULL, 3, 3, "T", "Table"},
  {"set", 1, DrfNone, TRetBlkP, NULL, 1, 6, "S", "Set"},
  {"kywdint", 0, DrfCnst, TRetDescP, ".i........................", 0, 0, "kywdint", "Kywdint"},
  {"kywdsubj", 0, DrfCnst, TRetDescP, "s.........................", 0, 0, "kywdsubj", "Kywdsubj"},
  {"kywdpos", 0, DrfCnst, TRetDescP, ".i........................", 0, 0, "kywdpos", "Kywdpos"},
  {"kywdany", 0, DrfCnst, TRetDescP, "siRcomcuwpC..nycrLTS......", 0, 0, "kywdany", "Kywdany"},
  {"kywdstr", 0, DrfCnst, TRetDescP, "s.........................", 0, 0, "kywdstr", "Kywdstr"},
  {"kywdhandler", 0, DrfCnst, TRetDescP, "siRcomcuwpC..nycrLTS......", 0, 0, "kywdhandler", "Kywdhandler"}};

int str_var = 0;
int trpd_tbl = 1;
int lst_elem = 2;
int tbl_dflt = 5;
int tbl_val = 4;

int num_cmpnts = 7;
struct typ_compnt typecompnt[7] = {
  {"str_var", 0, 0, 11, NULL},
  {"trpd_tbl", 0, 0, 12, NULL},
  {"lst_elem", 0, 1, 17, "LE"},
  {"tbl_key", 0, 0, 18, NULL},
  {"tbl_val", 1, 1, 18, "TV"},
  {"tbl_dflt", 2, 0, 18, NULL},
  {"set_elem", 0, 0, 19, NULL}};
