< ../../mkdefs

LIBSRC=ucode.icn lex.icn parser.icn tree.icn symboltable.icn oigram.icn preprocessor.icn evaluator.icn

LIBU=${LIBSRC:%.icn=%.u}

all:V: $LIBU

clean:V:
	rm -f *.u oigram.icn packages.txt

$LIBU: oigram.icn

%.u:Q: %.icn
       test $stem.u -nt $stem.icn || oit -sncW $LIBSRC

oigram.icn : oigram.y
	iyacc -k parser oigram.y
