< mkdefs

default:V:	all

all:V:
	@{ cd base ; mk }
	@{ cd lib ; mk }
	@{ cd apps ; mk }
	@{ cd examples ; mk }
	@{ cd riox ; mk }
        @{ 
           OI_FONT=p9:$font
           if(test -e fontinfo.txt) 
                ;
           if not
                if(oit -s ./mkfontinfo.icn -x >fontinfo.txt)
                     ;
                if not
                     rm -f fontinfo.txt
         }

clean:V:
	@{ cd base ; mk clean }
	@{ cd lib ; mk clean }
	@{ cd apps ; mk clean }
	@{ cd examples ; mk clean }
	@{ cd riox ; mk clean }

test:V:
        @{ cd test ; ./runtest.sh }

bmark:V:
        @{ cd bmark ; ./runbmark.sh }

libref:V:
	rm -rf libref
	mkdir libref
	oidoc -html -d -o libref -a
