< ../mkdefs

PROGS=browser canvasstate colors cursors directorydialogtest \
	dndtest dyncomps editor explorer filedialogtest \
	fonttest geturl grabtest imageview lslinks \
	multi selection sieve sizetest palette \
	sliders stock suggest tooltip treetest \
	ttexplorer fields flowterm bus lscookies \
	showtemplate cairotest lsxdg fl note ern

BIN=${PROGS:%=bin/%}

all:V: $BIN

clean:V:
	rm -f *.u packages.txt bin/*

bin/%: %.icn
	oit -sW -o $target $stem.icn
