< ../../../mkdefs

PROGSRC=`{ls *.icn}
PROGU=${PROGSRC:%.icn=%.u}
PROGS=${PROGSRC:%.icn=%}

all:V: $PROGS

clean:
	rm -f $PROGS *.u packages.txt

%: %.icn
        OIPATH=($OIPATH $OIHOME/apps/ivib)
	oit -so $stem $stem.icn
