< ../mkdefs

PROGS=  ieval fiximports memdebug memorytracker
BIN=${PROGS:%=../bin/%}

default:V:	all

all:V:   $BIN
	@{ cd ivib ; mk all }
	@{ cd oidoc ; mk all }

clean:V:
	rm -f $BIN *.u packages.txt
	@{ cd ivib ; mk clean }
	@{ cd oidoc ; mk clean }

../bin/%: %.icn
	oit -s -o $target $stem.icn
