include ../Makedefs

all :
	$(MAKE) -C incl all
	$(MAKE) -C iyacc all
	$(MAKE) -C ipl all
	$(MAKE) -C main all
	$(MAKE) -C gui all
	$(MAKE) -C xml all
	$(MAKE) -C parser all
	$(MAKE) -C native all

clean :
	$(MAKE) -C incl clean
	$(MAKE) -C iyacc clean
	$(MAKE) -C ipl clean
	$(MAKE) -C main clean
	$(MAKE) -C gui clean
	$(MAKE) -C xml clean
	$(MAKE) -C parser clean
	$(MAKE) -C native clean

etags :
	$(MAKE) -C incl etags
	$(MAKE) -C ipl etags
	$(MAKE) -C main etags
	$(MAKE) -C gui etags
	$(MAKE) -C xml etags
	$(MAKE) -C parser etags
	$(MAKE) -C native etags
