< ../../mkdefs

SRC=oidoc.icn outputter.icn htmloutputter.icn groffoutputter.icn
UFILES=${SRC:%.icn=%.u}
PROG=../../bin/oidoc

all:V:	$PROG

clean:
	rm -f $PROG *.u packages.txt

$PROG:  $UFILES
	oit -sn -o $target $UFILES

%.u:Q: %.icn
	test $stem.u -nt $stem.icn || oit -snc $SRC
