/* src/h/auto.h.  Generated by configure.  */
/* define's for zlib, jpeg, opengl, etc. */

/* define as 1 if we have Zlib/libz/whatever */
#define HAVE_LIBZ 1

/* define as 1 if we have jpeg */
#define HAVE_LIBJPEG 1

/* define as 1 if we have opengl */
#define HAVE_LIBGL 1

/* define as 1 if we have odbc */
/* #undef HAVE_LIBIODBC */

/* define as 1 if we have getrlimit */
#define HAVE_GETRLIMIT 1

/* define as 1 if we have setrlimit */
#define HAVE_SETRLIMIT 1

/* define as 1 if we have a timezone variable */
#define HAVE_TIMEZONE 1

/* define as 1 if struct tm has a tm_zone field */
#define HAVE_STRUCT_TM_TM_ZONE 1

/* define as 1 if struct tm has a tm_gmtoff field */
/* #undef HAVE_STRUCT_TM_TM_GMTOFF */

/* define as 1 if tzname exists */
/* #undef HAVE_TZNAME */

/* define as 1 if X11 is found */
/* #undef HAVE_LIBX11 */

/* define as 1 if strerror exists */
/* #undef HAVE_STRERROR */

/* define as 1 if sys_nerr exists */
/* #undef HAVE_SYS_NERR */

/* define as 1 if sys_errlist exists */
/* #undef HAVE_SYS_ERRLIST */

#define NoProfil
#define NoEventMon
#define HAVE_STRERROR


