< ../mkdefs

OFILES=\
	rio.$O\
	data.$O\
	fsys.$O\
	scrl.$O\
	time.$O\
	util.$O\
	wctl.$O\
	wind.$O\
	xfid.$O\
	frbox.$O\
	frdelete.$O\
	frdraw.$O\
	frinit.$O\
	frinsert.$O\
	frptofchar.$O\
	frselect.$O\
	frstr.$O\
	frutil.$O\

all:V:  $O.out

$O.out:  $OFILES
        $LD $OFILES
        cp $O.out $OI_BIN/riox

clean:V:	
        rm -f $OFILES $O.out
