< ../mkdefs

OFILES=\
	rio.$O\
	data.$O\
	fsys.$O\
	scrl.$O\
	time.$O\
	util.$O\
	wctl.$O\
	wind.$O\
	xfid.$O\
	frbox.$O\
	frdelete.$O\
	frdraw.$O\
	frinit.$O\
	frinsert.$O\
	frptofchar.$O\
	frselect.$O\
	frutil.$O\

PROG=	../bin/riox

all:V:  $O.out

$O.out:  $OFILES
	rm -f $PROG
	$LD -o $PROG $OFILES

clean:V:	
	rm -f $OFILES $PROG
